apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: kubiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: controller
          image: lola69456/controller:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080