kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test
rules:
  - apiGroups: [""]
    resources: ["deployments", "pods", "pods/exec", "namespaces", "persistentvolumes", "persistentvolumeclaims", "storageclasses"]
    verbs: ["get", "list", "delete", "patch", "create", "update"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments", "deployments/scale", "persistentvolumes", "persistentvolumeclaims", "storageclasses"]
    verbs: ["get", "list", "delete", "patch", "create", "update"]
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: ["", "apps"] # "" indicates the core API group
    resources: ["deployments", "pods", "namespaces", "persistentvolumes", "persistentvolumeclaims", "storageclasses"]
    verbs: ["get", "list", "delete", "patch", "create", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubiki
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io