apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pvc
spec:
  storageClassName: mystorage
  capacity:
    storage: 25Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/my-storage"