apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: kubiki
spec:
  storageClassName: mystorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Mi