apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-name
spec:
  storageClassName: mystorage
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/my-pvName"