apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image
  namespace: kubiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-image
  template:
    metadata:
      labels:
        app: test-image
    spec:
      containers:
        - name: test-image
          image: hello-world
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"