apiVersion: apps/v1
kind: Deployment
metadata:
  name: util-service-1
  namespace: kubiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: util-service-1
  template:
    metadata:
      labels:
        app: util-service-1
    spec:
      containers:
        - name: util-service-1
          image: ra77us/utils-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: util-service-1
  namespace: kubiki
spec:
  selector:
    app: util-service-1
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30111