apiVersion: apps/v1
kind: Deployment
metadata:
  name: util-service-2
  namespace: kubiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: util-service-2
  template:
    metadata:
      labels:
        app: util-service-2
    spec:
      containers:
        - name: util-service-2
          image: ra77us/utils-service:latest
          resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.5"
          env:
          - name: test2.slow
            value: "true"
          - name: test3.num
            value: "43"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: util-service-2
  namespace: kubiki
spec:
  selector:
    app: util-service-2
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31022