apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-adapter
  namespace: kubiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-adapter
  template:
    metadata:
      labels:
        app: metrics-adapter
    spec:
      containers:
        - name: metrics-adapter
          image: ra77us/utils-ma:latest
          env:
          - name: backend
            value: http://hephaestus-gui.hephaestus:8080
          - name: kubernetes-management
            value: http://kubernetes-management.kubernetes-management:8097
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-adapter
  namespace: kubiki
spec:
  selector:
    app: metrics-adapter
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31111