apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: kubiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: heidiks/rabbitmq-delayed-message-exchange:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  namespace: kubiki
spec:
  selector:
    app: rabbit
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 5672
      name: "queue"
      targetPort: 5672
      nodePort: 30672
    - protocol: "TCP"
      port: 15672
      name: "admin"
      targetPort: 15672
      nodePort: 31672