apiVersion: apps/v1
kind: Deployment
metadata:
  name: complex-service
  namespace: kubiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complex-service
  template:
    metadata:
      labels:
        app: complex-service
    spec:
      containers:
        - name: kinia-service
          image: lola69456/complex-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: complex-service
  namespace: kubiki
spec:
  selector:
    app: complex-service
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 32233